### ISSUE TITLE
m4a files not being made correctly for duration extraction

### ISSUE THREAD

**Issue by kymckay** [sk-zk/yashbot#1]
Note that I've updated the youtube-dl.exe (via `youtube-dl -U`) and this error is occurring when trying to process an unprocessed video (error snippet at bottom). I've taken a look at the relevant code in visual studio, but it's hard to debug as I've had trouble getting the required libraries set up.

For example, I'm assuming that `File.Create()` isn't returning a `FileStream` like it would do with the `System.IO` library because the `File` class defined is in one of the namespaces I'm missing (and hence the error isn't because the file is locked).

```
Looking up M7QmAEN5-eQ
Processing M7QmAEN5-eQ now
Downloading audio
Analyzing song
Something went wrong:
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFo
undException: Could not find file 'C:\Users\<MyUser>\AppData\Roaming\yashbot\M7QmAEN
5-eQ.m4a'.
   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyl
e propertiesStyle)
   at yashbot.Program.<ProcessVideo>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at yashbot.Program.Main(String[] args)
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not find file '
C:\Users\<MyUser>\AppData\Roaming\yashbot\M7QmAEN5-eQ.m4a'.
File name: 'C:\Users\<MyUser>\AppData\Roaming\yashbot\M7QmAEN5-eQ.m4a'
   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyl
e propertiesStyle)
   at yashbot.Program.<ProcessVideo>d__7.MoveNext()<---
```

I thought this might be some sort of permissions issue, but running cmd as admin didn't seem to fix it.

**Comment by sk-zk** [comment]
If TagLib.File.Create throws an exception, youtube-dl probably failed somewhere along the way. In this case, ffmpeg.exe and ffprobe.exe might be missing. You can download them [here](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.2.2-win64-static.zip).

**Comment by kymckay** [comment]
Ah apparently I had a different version of those exe's (comparing the MD5) which is probably what was causing the issue. The ones I had were from the latest windows 64bit version on the ffmpeg site

**Comment by kymckay** [comment]
Nevermind :stuck_out_tongue: Still getting the same error with those exe's

**Comment by sk-zk** [comment]
Hmm. Can you post the console output for `youtube-dl VcEvFfne7Tk -f bestaudio -x --audio-format m4a --add-metadata`  ?

**Comment by kymckay** [comment]
Sure thing:
```
[youtube] VcEvFfne7Tk: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL
: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
```

**Comment by sk-zk** [comment]
This might work: https://github.com/rg3/youtube-dl/issues/7309#issuecomment-172354527

**Comment by kymckay** [comment]
Can confirm that following those instructions has fixed the issue :+1:

I had a load of expired certificates from 2014!
